@TaskManagerBackEnd_HostAddress = https://localhost:7186
###
GET {{TaskManagerBackEnd_HostAddress}}/user/TestRequest
Accept: application/json

###
POST {{TaskManagerBackEnd_HostAddress}}/user/CreateUser
Content-Type: application/json

{
  "Email": "Maria@example.com",
  "Password": "password123",
  "Name": "Maria",
  "Post": "Developer",
  "Enabled": true,
  "IdTeam": 1
}

###

###
PUT {{TaskManagerBackEnd_HostAddress}}/user/UpdateUser
Content-Type: application/json

{
  "IdUser": 3,
  "Email": "JohnDoe@example.com",
  "Name": "John Doe",
  "Post": "Developer",
  "Enabled": true
}

###

PUT {{TaskManagerBackEnd_HostAddress}}/User/UpdatePassword
Content-Type: application/json

{
  "IdUser": 6,
  "NewPassword": "password123456"
}

###
POST {{TaskManagerBackEnd_HostAddress}}/User/Login
Content-Type: application/json

{
  "Email": "Maria@example.com",
  "Password": "password123456"
}

###
POST {{TaskManagerBackEnd_HostAddress}}/Team/CreateTeam
Content-Type: application/json

{
  "Name": "Financial Team",
  "Enabled": true
}

###

###
POST {{TaskManagerBackEnd_HostAddress}}/User/Login
Content-Type: application/json

{
  "Email": "Maria@example.com",
  "Password": "password123456"
}

> {%client.global.set("auth_token", response);%}

### Authorization by token, part 2. Use token to authorize.
GET {{TaskManagerBackEnd_HostAddress}}/user/TestRequest
Accept: application/json
Authorization: Bearer {{auth_token}}

